version: '3.3'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mongo:27017
    volumes:
      - ./backend/uri:/usr/src/app/uri 


#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#
#    environment:
#      - DANGEROUSLY_DISABLE_HOST_CHECK=true
#    ports:
#      - "3000:3000"
volumes:
  mongo_data:
